# Generated by Django 4.1.1 on 2022-10-05 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prisonapp', '0004_crime_crimedetails_crime_crimetitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crime',
            old_name='cell',
            new_name='cellno',
        ),
    ]
