# Generated by Django 4.1.1 on 2022-10-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisonapp', '0008_finance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='vtime',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='visitor',
            name='vdate',
            field=models.DateTimeField(),
        ),
    ]
